version: "3.3"

services :
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=geoInventario
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo_data:/data/db